
project_id = "tnurlgbvfsxwqgwxamni"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "http://localhost:3000"
additional_redirect_urls = [
  "https://localhost:3000",
  "http://localhost:3000/**",
  "https://localhost:3000/**"
]
jwt_expiry = 3600
enable_signup = true
enable_confirmations = false

[functions.whatsapp-api]
verify_jwt = false

[functions.n8n-api]
verify_jwt = false

[functions.create-n8n-workflow]
verify_jwt = false

[functions.mercado-pago-subscribe]
verify_jwt = false

[functions.mercado-pago-webhook]
verify_jwt = false

[functions.update-register-function]
verify_jwt = false

[functions.update-register-function-sql]
verify_jwt = false
